version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: bus-tracking-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root@123
      MYSQL_DATABASE: bus_tracking
    ports:
      - "33306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  api:
    build: .
    container_name: bus-tracking-api
    restart: always
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root@123
      DB_NAME: bus_tracking

volumes:
  mysql_data:
